server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://192.168.1.94:3306/dzy2.0?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=CST&autoReconnect=true
    username: dzyproject
    password: mO4E2ohE
    driver-class-name: com.mysql.jdbc.Driver
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000



  jackson:
    locale: zh_CN
    time-zone: GMT+8
#  resources:
#    static-locations: classpath:/**

  #异常邮件通知
  mail:
    host: smtp.qq.com #1159142560@qq.com
    username: 1159142560@qq.com
    password: fmgqklsbnkmnjegh
    properties:
      mail:
        smtp:
          auth: true
          startls:
            enable: true
            required: true


mvc:
  throw-exception-if-no-handler-found: true

freemarker:
  template-loader-path:
    -classpath: /templates/
  suffix: .ftl
  enabled: true
  cache: false
  charset: UTF-8
  content-type: text/html
  allow-request-override: false
  check-template-location: true
  expose-request-attributes: false
  expose-session-attributes: false
  expose-spring-macro-helpers: false

alarm:
  email: 2457924535@qq.com




mybatis:
  mapper-locations : classpath:mapper/*.xml
  type-aliases-package: com.c1801.spring.dzy.model
  configuration:
    map-underscore-to-camel-case: true

